######################################
### Configure programming language ###
######################################
language: java

##################################
### Make sure using Oracle JDK ###
##################################
jdk:
- oraclejdk8

###################################
### Disable Email notifications ###
###################################
notifications:
  email: false

###########################
### Actual Build Script ###
###########################
script:
- bash buildViaTravis.sh

##################
### Deployment ###
##################
deploy:
  provider: script
  script: bash installViaTravis.sh
  on:
    branch: master